repos:
  - repo: local
    hooks:
      - id: ruff-check
        name: Ruff Check
        entry: ruff check --fix
        language: system
        files: \.py$
        require_serial: false
        
      - id: ruff-format
        name: Ruff Format
        entry: ruff format
        language: system
        files: \.py$
        require_serial: false
